### PR TITLE
Dedicate this to public domain

### PR DESCRIPTION
**Pull request by Huy-Ngo**
This work is useless anyway so I think we can dedicate this to public domain.

### CODE REVIEW

**Review by dinhanhx — APPROVED** [review]
LGTM

**Comment by Huy-Ngo** [comment]
I expected you to not accept this or switch to some permissive license like MIT ;)

**Comment by dinhanhx** [comment]
>This work is useless

**Comment by Huy-Ngo** [comment]
idk you may want to add it to your profile and thus retaining some copyright

**Pull request merged**
