### PR TITLE
Upload data

### PR DESCRIPTION
**Pull request by 9a24f0**
Sorry I forgot to open PR for this

### CODE REVIEW

**Review by dinhanhx — COMMENTED** [review]
LGTM but I will wait for @huonglarne

**Comment by 9a24f0** [comment]
Closed as not needed anymore

**Comment by dinhanhx** [comment]
> Closed as not needed anymore

I want you focus on YOUR internship

**Comment by 9a24f0** [comment]
> I want you focus on YOUR internship

I do have private repo on gh to save things remotely, I just can't stand that PR still on top of my gh page.

**Comment by dinhanhx** [comment]
> > I want you focus on YOUR internship
> 
> I do have private repo on gh to save things remotely, I just can't stand that PR still on top of my gh page.

OKAY THEN

**Comment by Huy-Ngo** [comment]
> > I do have private repo on gh to save things remotely, I just can't stand that PR still on top of my gh page.

I suggest you host your private code on code hosting services that
respects your digital freedom and privacy as well as freedom of
speech, especially if you don't have any obligation to use GitHub due
to your team members only using GitHub.
Codeberg, Gittea, and SourceHut are some of popular choices. I
wouldn't urge you if you don't want to change, though. (Ironic of me
to use Gmail to reply to this thread)

> OKAY THEN

DON'T SCREAM MY EARS HURT

(^^^ This is my main reason for replying in this thread.)

**Comment by dinhanhx** [comment]
> OKAY THEN
> DON'T SCREAM MY EARS HURT (^^^ This is my main reason for replying in this thread.)

okay then

**Comment by Huy-Ngo** [comment]
> okay then

👌

**Comment by dinhanhx** [comment]
> okay then
> 👌

Have a good day.

**Pull request closed without merging**
